language: node_js
node_js:
    - 'node' # latest

cache:
    yarn: true
    directories:
        - node_modules

install:
    - yarn install --frozen-lockfile --non-interactive

script:
    - yarn format --check
